/* output.h */

void print_params(FILE *fp);
void print_opfiles(FILE *fp);
void start_output();
void step_output(int t);
void run_output();
void fprint_pop(FILE *fp);
void fprint_threshrange(FILE *fp);
void fprint_stats(FILE *fp);
void fprint_stepthresh(FILE *fp, int t);
void fprint_stepsummary(FILE *fp, int t);
void fprint_stepdemand(FILE *fp, int t);
void fprint_steptaskdemand(FILE *fp, int t);
void fprint_steptaskcounts(FILE *fp, int t);
void fprint_steptaskthresh(FILE *fp, int t);
void fprint_steptargetpath(FILE *fp, int t);
void fprint_steptrackerpath(FILE *fp, int t);
void fprint_stepnorthsouth(FILE *fp, int t);
void fprint_stepeastwest(FILE *fp, int t);
void fprint_stepdistance(FILE *fp, int t);
void fprint_finalstats(FILE *fp);
void fprint_stepagentaction(FILE *fp, int t);
void fprint_stepagentactionwtime(FILE *fp, int t);
void fprint_stepagentactionxyz(FILE *fp, int t);
void fprint_stepagentmintask(FILE *fp, int t);
void fprint_stepagentmintaskaction(FILE *fp, int t);
void fprint_finalagent(FILE *fp);
void fprint_finaltask(FILE *fp);
void fprint_finalthreshswitch(FILE *fp);
void fprint_finalthreshact(FILE *fp);
void fprint_agentthresh(FILE *fp, int n);
void fprint_intensities(FILE *fp);
void fprint_stephistnorth(FILE *fp, int timestep);
void fprint_stephistsouth(FILE *fp, int timestep);
void fprint_stephisteast(FILE *fp, int timestep);
void fprint_stephistwest(FILE *fp, int timestep);
void fprint_intensityrange(FILE *fp);
void fprint_stepintensity(FILE *fp, int t);
void fprint_stepthreshnorth(FILE *fp, int t);
void fprint_stepthreshsouth(FILE *fp, int t);
void fprint_stepthresheast(FILE *fp, int t);
void fprint_stepthreshwest(FILE *fp, int t);
void fprint_stepintensitynorth(FILE *fp, int t);
void fprint_stepintensitysouth(FILE *fp, int t);
void fprint_stepintensityeast(FILE *fp, int t);
void fprint_stepintensitywest(FILE *fp, int t);
void fprint_responseprob(FILE *fp);
void fprint_stepprobnorth(FILE *fp, int t);
void fprint_stepprobeast(FILE *fp, int t);
void fprint_stepprobsouth(FILE *fp, int t);
void fprint_stepprobwest(FILE *fp, int t);
